module-name: "oredata"

spring:
  main:
    allow-circular-references: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: "bankingproject"
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/oredata"
    username: postgres
    password: 12345
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000

logging:
  level:
    root: info
    org.apache.tomcat.level: warn
    org.apache.tomcat.util.net.level: warn
    com.zaxxer.hikari.HikariConfig: debug
    com.zaxxer.hikari: trace
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

server:
  port: 8080
