module-name: "oredata"

spring:
  main:
    allow-circular-references: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: "bankingproject"
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  # H2 Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000

logging:
  level:
    root: info
    org.apache.tomcat:
      level: warn
    org.apache.tomcat.util.net:
      level: warn
    com.zaxxer.hikari.HikariConfig: debug
    com.zaxxer.hikari: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8080
